title: "Mohammed JAMAI"
description: "Mechatronics Engineer specializing in modeling, simulation, real-time validation, FPGA and embedded systems."
author: "Mohammed JAMAI"

url: "https://m-jamai.github.io"
baseurl: "/m-jamai"

markdown: kramdown

plugins:

* jekyll-seo-tag

exclude:

* README.md
* Gemfile
* Gemfile.lock
