title: "Mohammed JAMAI"
description: "Mechatronics Engineer specialized in MATLAB/Simulink, Real-Time Simulation, HIL, FPGA and Embedded Systems."
author: "Mohammed JAMAI"

theme: jekyll-theme-minimal

url: "https://m-jamai.github.io"
baseurl: ""

logo: ""
show_downloads: false

lang: "en"

github_username: "m-jamai"
email: "jamai-mohammed@hotmail.com"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
